/*
 * KeyVisWin.java
 *
 * Created on 15 luty 2007, 23:30
 */

package org.keyfrog.keyvis;

import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

import java.util.GregorianCalendar;

/**
 *
 * @author Sebastian Gniazdowski
 */
public class KeyVisWin extends javax.swing.JFrame {
    private LineChartFactory m_lineChartFactory;
    
    /** Creates new form KeyVisWin */
    public KeyVisWin() {
        initComponents();
        
        // 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jComboChartType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jTextYearBeg = new javax.swing.JTextField();
        jTextMonthBeg = new javax.swing.JTextField();
        jTextDayBeg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextDayEnd = new javax.swing.JTextField();
        jTextMonthEnd = new javax.swing.JTextField();
        jTextYearEnd = new javax.swing.JTextField();
        jTextDatabasePath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keyvis");
        jPanel1.setLayout(new java.awt.BorderLayout());

        jComboChartType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line chart", "Hour accumulated line chart", "Day accumulated line chart", "Week accumulated line chart", "Month accumulated line chart" }));
        jComboChartType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboChartTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Chart type");

        jButtonUpdate.setText("Update chart");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jTextYearBeg.setText("2013");

        jTextMonthBeg.setText("01");

        jTextDayBeg.setText("15");

        jLabel2.setText("Start date");

        jLabel3.setText("End date");

        jTextDayEnd.setText("15");

        jTextMonthEnd.setText("03");

        jTextYearEnd.setText("2013");

        jTextDatabasePath.setText("/tmp/keyfrog.db");

        jLabel4.setText("Database");

        jMenu1.setText("Menu");
        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuAbout);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboChartType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextMonthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextDayBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextMonthBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextYearBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDatabasePath, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUpdate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboChartType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextDatabasePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDayBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMonthBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextYearBeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMonthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jButtonUpdate))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        AboutWin aboutWin = new AboutWin();
        aboutWin.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jComboChartTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboChartTypeActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jComboChartTypeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // Get chart type
        int idx = jComboChartType.getSelectedIndex();
        switch(idx) {
            // Simple line chart
            case 0:
                    m_lineChartFactory.setChartType(LineChartFactory.SIMPLE);
                    break;
            // Accu chart (hour)
            case 1:
                    m_lineChartFactory.setChartType(LineChartFactory.ACCUMULATE);
                    m_lineChartFactory.setAccumulationRange(LineChartFactory.HOUR);
                    break;
            // Accu chart (day)
            case 2:
                    m_lineChartFactory.setChartType(LineChartFactory.ACCUMULATE);
                    m_lineChartFactory.setAccumulationRange(LineChartFactory.DAY);
                    break;
            // Accu chart (week)
            case 3:
                    m_lineChartFactory.setChartType(LineChartFactory.ACCUMULATE);
                    m_lineChartFactory.setAccumulationRange(LineChartFactory.WEEK);
                    break;
            // Average chart (month)
            case 4:
                    m_lineChartFactory.setChartType(LineChartFactory.ACCUMULATE);
                    m_lineChartFactory.setAccumulationRange(LineChartFactory.MONTH);
                    break;
        }
        
        // Get dataset range
        // FIXME: input validation!
        int day = Integer.parseInt(jTextDayBeg.getText());
        int month = Integer.parseInt(jTextMonthBeg.getText());
        int year = Integer.parseInt(jTextYearBeg.getText());
        int start_ts = (int) (new GregorianCalendar(year, month - 1, day, 0, 0, 0).getTimeInMillis() / 1000L);
        day = Integer.parseInt(jTextDayEnd.getText());
        month = Integer.parseInt(jTextMonthEnd.getText());
        year = Integer.parseInt(jTextYearEnd.getText());
        int end_ts = (int) (new GregorianCalendar(year, month - 1, day, 23, 59, 59).getTimeInMillis() / 1000L);
        m_lineChartFactory.setDataRange(start_ts, end_ts);
        
        // Get sqlite database path
        m_lineChartFactory.setDatabasePath(jTextDatabasePath.getText());
        
        JFreeChart chart = m_lineChartFactory.produceChart();
        setChart(chart);
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    
    public void setLineChartFactory(LineChartFactory lineChartFactory) {
        m_lineChartFactory = lineChartFactory;
    }
    
    public void drawEmptyChart() {
        JFreeChart chart = m_lineChartFactory.createChart(new TimeSeriesCollection());
        setChart(chart);
    }
    
    public void setChart(JFreeChart chart) {
        ChartPanel chartPanel = new ChartPanel(chart);        
        chartPanel.setMouseZoomable(true, false);
        setMainPanel(chartPanel);
    }
    
    public void setMainPanel(javax.swing.JPanel panel) {
        jPanel1.removeAll();
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public void setDatabasePath(String databasePath) {
        jTextDatabasePath.setText(databasePath);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyVisWin().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboChartType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDatabasePath;
    private javax.swing.JTextField jTextDayBeg;
    private javax.swing.JTextField jTextDayEnd;
    private javax.swing.JTextField jTextMonthBeg;
    private javax.swing.JTextField jTextMonthEnd;
    private javax.swing.JTextField jTextYearBeg;
    private javax.swing.JTextField jTextYearEnd;
    // End of variables declaration//GEN-END:variables
    
}
